### ISSUE TITLE
Add special ability to characters

### ISSUE THREAD

**Issue by tul1** [tul1/avalon-rs#10]

**Comment by julianmateu** [comment]
What special abilities are you referring to?

**Comment by tul1** [comment]
Haha actually this is already covered with `is_seen_by` and `can_see`, special abilities are just vision power. Except for the `Assassin` that she can kill `Merlin` at the end of the game.

**Comment by julianmateu** [comment]
Yes. Since the `Assasin` is a special case, which has to do more with the Game stage and not with a special power of the character, I propose we implement that at the end game phase. We still have to come up with a design for that, but for now I don't think we need to add extra methods to the `Character` trait.
