### ISSUE TITLE
Implement an iterator for quest_objectives in Board

### ISSUE THREAD

**Issue by tul1** [tul1/avalon-rs#11]
In
```
pub struct Board {
    pub quest_objectives: Vec<QuestObjective>,
}
```
Implement iterator methods following this:
https://doc.rust-lang.org/book/ch13-02-iterators.html#the-iterator-trait-and-the-next-method

**Comment by julianmateu** [comment]
What is the purpose of this? To call `board.iter()` instead of `board.ques_objectives.iter()`?

I support the idea of implementing common traits as a good way of familiarising ourselves with Rust, but from a logical perspective I'm a little unsure that the `Board` is iterable, given that it could potentially contain other data (if you thing about how you would use the english language to refer to a board, it doesn't make much sense to say "give me your elements"), and you can get the quest objectives by explicitly declaring your intention to do so with `board.ques_objectives.iter()`. If that were the case I would probably suggest renaming the class.

**Comment by tul1** [comment]
`ques_objectives` seems to be a sequence of events or data and, IMHO, it makes from the functional point of view to have it implemented as iterator. We could take profit of methods like `next()` to iterate, `enumerate` or even `map` to initialize it or applying closures. 
Furthermore, I think that it could allow us to build more compact functional code when when we'll use Board in an upper level entity.
What do you think @julianmateu @manuelaguirre ?

**Comment by manuelaguirre** [comment]
I think that when we need the iterator for quest_objectives we can just make one with the to_iter(), method, given that rust already provides logic for work on vectors as iterables.

**Comment by tul1** [comment]
Well, nevermind, vec implement iter() so the class attr has already implemented  the iterable trait. However, I do have a remark on leaving to the top level all the hard work. I think that as much as we encapsulate entities behavior the cleaner and more self expressive the crate it will be for the user. And that's should be one of our goals too.

**Comment by julianmateu** [comment]
I agree with that. For now all these are internal classes though, we should make a clear API design once we have a more advanced implementation, and at that point we will decide which classes are exposed to users of this crate.
